export const HandbookData = [
  {
    id: 6,
    chapter: 'CHAPTER ONE',
    is_bold: true,
    is_capital_letter: true,
    is_italic: false,
    sub_category: [
      {
        id: 150,
        category: {
          id: 6,
          chapter: 'CHAPTER ONE',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'General Information',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [
          {
            id: 288,
            title: null,
            sub_title: null,
            number: null,
            body: 'Joseph Ayo Babalola University was established by the Christ Apostolic Church following a divine directive to its former President, Pastor E.H.L. Olusheye. The Christ Apostolic Church is a wholly indigenous Christian Pentecostal denomination with no foreign affiliations but has spread to the 68 West and Southern Africa, Europe, the United States of 68 America, Canada etc. Christ Apostolic Church is not a new comer to education project in Nigeria. It established its first primary school in 1934 and by 1979, when the state governments took over the administration and financing of primary and post primary schools, the Church had established over 150 educational institutions at various levels all over the country.',
            is_bold: false,
            is_center: false,
            is_list: false,
            is_paragraph: false,
            is_number: false,
            is_italic: false,
            is_table: false,
            is_capital_letter: false,
            is_another_content: false,
            sub_category: {
              id: 150,
              name: 'General Information',
              is_bold: false,
              is_capital_letter: false,
              is_italic: false,
              category: 6,
            },
            list_contents: [],
            list_table_header: [],
            list_sub_content: [],
          },
        ],
      },
      {
        id: 151,
        category: {
          id: 6,
          chapter: 'CHAPTER ONE',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'The Name "Joseph Ayo Babalola University"',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [
          {
            id: 289,
            title: null,
            sub_title: null,
            number: null,
            body: 'The Christ Apostolic Church believes strongly in the leading of the Holy Spirit in its programmes and activities. Just as the decision to establish the University was inspired by the Holy Spirit, the name of the University was divinely given to immortalize one of the greatest revivalists and apostles of God in this age, Apostle Joseph Ayo Babalola. He was born at Odo- Owa in Kwara State but his call was at Ikeji Arakeji, Osun State. For over three decades, his missionary activities traversed the South-Western part of the country, Kwara State and Ghana preaching the word of God and healing the sick and the afflicted. His revival resulted in a mass movement that attracted the attention of the then colonial government, which monitored his movements and filed annual reports on his activities to the British Government beyond 1940s. Apostle Joseph Ayo Babalola was reputed to have raised the dead; he became a patriarch of Christ Apostolic Church, the mother of Pentecostal Churches in Nigeria.',
            is_bold: false,
            is_center: false,
            is_list: false,
            is_paragraph: false,
            is_number: false,
            is_italic: false,
            is_table: false,
            is_capital_letter: false,
            is_another_content: false,
            sub_category: {
              id: 151,
              name: 'The Name "Joseph Ayo Babalola University"',
              is_bold: false,
              is_capital_letter: false,
              is_italic: false,
              category: 6,
            },
            list_contents: [],
            list_table_header: [],
            list_sub_content: [],
          },
        ],
      },
      {
        id: 152,
        category: {
          id: 6,
          chapter: 'CHAPTER ONE',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Location of Joseph Ayo Babalola University',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [
          {
            id: 290,
            title: null,
            sub_title: null,
            number: null,
            body: "Joseph Ayo Babalola University is located at Ikeji Arakeji on the spot where Apostle Joseph Ayo Babalola received his call. It covers over 160 hectares of land, part of which was used as Christ Apostolic Church International Miracle Camp. Ikeji Arakeji is located in Osun State, along Ilesa-Akure Road. The Campus is on a virgin land but close to three major cities namely, Osogbo, Ilesa and Akure. Apart from its accessibility to other cities in the South western part of the country, the Ilesa-Akure road is a popular route to the northern and eastern parts of the country. Joseph Ayo Babalola University is about three-hour drive to the nation's largest international airport in Lagos, the commercial capital of Nigeria. It is close enough to a number of cities where staff and students could carry out requisite activities.",
            is_bold: false,
            is_center: false,
            is_list: false,
            is_paragraph: true,
            is_number: false,
            is_italic: false,
            is_table: false,
            is_capital_letter: false,
            is_another_content: false,
            sub_category: {
              id: 152,
              name: 'Location of Joseph Ayo Babalola University',
              is_bold: false,
              is_capital_letter: false,
              is_italic: false,
              category: 6,
            },
            list_contents: [],
            list_table_header: [],
            list_sub_content: [],
          },
          {
            id: 291,
            title: null,
            sub_title: null,
            number: null,
            body: 'Ikeji Arakeji provides a serene atmosphere for scholarship; its closeness to the Church prayer camp also provides a suitable environment for meditation and communion with the Creator. Indeed its virtual isolation from the hurly burly of city life, makes it ideal for proper academic activities, including research, and character training.',
            is_bold: false,
            is_center: false,
            is_list: false,
            is_paragraph: true,
            is_number: false,
            is_italic: false,
            is_table: false,
            is_capital_letter: false,
            is_another_content: false,
            sub_category: {
              id: 152,
              name: 'Location of Joseph Ayo Babalola University',
              is_bold: false,
              is_capital_letter: false,
              is_italic: false,
              category: 6,
            },
            list_contents: [],
            list_table_header: [],
            list_sub_content: [],
          },
        ],
      },
      {
        id: 153,
        category: {
          id: 6,
          chapter: 'CHAPTER ONE',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Objectives of the University',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 154,
        category: {
          id: 6,
          chapter: 'CHAPTER ONE',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'University Motto',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 155,
        category: {
          id: 6,
          chapter: 'CHAPTER ONE',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'University Logo',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 156,
        category: {
          id: 6,
          chapter: 'CHAPTER ONE',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Our Vision',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 157,
        category: {
          id: 6,
          chapter: 'CHAPTER ONE',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Our Mission',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 158,
        category: {
          id: 6,
          chapter: 'CHAPTER ONE',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Our Philosophy',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 159,
        category: {
          id: 6,
          chapter: 'CHAPTER ONE',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Residence',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 160,
        category: {
          id: 6,
          chapter: 'CHAPTER ONE',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'University Campus',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
    ],
  },
  {
    id: 7,
    chapter: 'CHAPTER TWO',
    is_bold: true,
    is_capital_letter: true,
    is_italic: false,
    sub_category: [
      {
        id: 161,
        category: {
          id: 7,
          chapter: 'CHAPTER TWO',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Administrative Organ',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 162,
        category: {
          id: 7,
          chapter: 'CHAPTER TWO',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Board of Trustees',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 163,
        category: {
          id: 7,
          chapter: 'CHAPTER TWO',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Council and its Committees',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 164,
        category: {
          id: 7,
          chapter: 'CHAPTER TWO',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Senate',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 165,
        category: {
          id: 7,
          chapter: 'CHAPTER TWO',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Congregation',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 166,
        category: {
          id: 7,
          chapter: 'CHAPTER TWO',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Convocation',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 167,
        category: {
          id: 7,
          chapter: 'CHAPTER TWO',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Principal Officers of the University',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 168,
        category: {
          id: 7,
          chapter: 'CHAPTER TWO',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Organization of Academic and Research Activities',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
    ],
  },
  {
    id: 8,
    chapter: 'CHAPTER THREE',
    is_bold: true,
    is_capital_letter: true,
    is_italic: false,
    sub_category: [
      {
        id: 169,
        category: {
          id: 8,
          chapter: 'CHAPTER THREE',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Spiritual Life',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 170,
        category: {
          id: 8,
          chapter: 'CHAPTER THREE',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Objectives',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 171,
        category: {
          id: 8,
          chapter: 'CHAPTER THREE',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Religious Activities on Campus',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
    ],
  },
  {
    id: 9,
    chapter: 'CHAPTER FOUR',
    is_bold: true,
    is_capital_letter: true,
    is_italic: false,
    sub_category: [
      {
        id: 172,
        category: {
          id: 9,
          chapter: 'CHAPTER FOUR',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Academic Life',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 173,
        category: {
          id: 9,
          chapter: 'CHAPTER FOUR',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Academic Programmes',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 174,
        category: {
          id: 9,
          chapter: 'CHAPTER FOUR',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Status of Courses',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 175,
        category: {
          id: 9,
          chapter: 'CHAPTER FOUR',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Registration of Courses and Class Attendance',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 176,
        category: {
          id: 9,
          chapter: 'CHAPTER FOUR',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: "Students' Performance/Evaluation",
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 177,
        category: {
          id: 9,
          chapter: 'CHAPTER FOUR',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Evaluation of Academic Performance',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 178,
        category: {
          id: 9,
          chapter: 'CHAPTER FOUR',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Requirements for Graduation',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 179,
        category: {
          id: 9,
          chapter: 'CHAPTER FOUR',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Student Industrial Work Experience Scheme (SIWES)',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 180,
        category: {
          id: 9,
          chapter: 'CHAPTER FOUR',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Eligibility for Examination',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 181,
        category: {
          id: 9,
          chapter: 'CHAPTER FOUR',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Academic Misconduct/Examination Malpractice',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 182,
        category: {
          id: 9,
          chapter: 'CHAPTER FOUR',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'University Library',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
    ],
  },
  {
    id: 10,
    chapter: 'CHAPTER FIVE',
    is_bold: true,
    is_capital_letter: true,
    is_italic: false,
    sub_category: [
      {
        id: 183,
        category: {
          id: 10,
          chapter: 'CHAPTER FIVE',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Social Life',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 184,
        category: {
          id: 10,
          chapter: 'CHAPTER FIVE',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Introductory Remarks',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 185,
        category: {
          id: 10,
          chapter: 'CHAPTER FIVE',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Relationship between Opposite Sex',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 186,
        category: {
          id: 10,
          chapter: 'CHAPTER FIVE',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Organization of Private Parties',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 187,
        category: {
          id: 10,
          chapter: 'CHAPTER FIVE',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'University Organized Social Activities',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 188,
        category: {
          id: 10,
          chapter: 'CHAPTER FIVE',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Academic Association Week',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
    ],
  },
  {
    id: 11,
    chapter: 'CHAPTER SIX',
    is_bold: true,
    is_capital_letter: true,
    is_italic: false,
    sub_category: [
      {
        id: 189,
        category: {
          id: 11,
          chapter: 'CHAPTER SIX',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Code of Conduct for Students',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 190,
        category: {
          id: 11,
          chapter: 'CHAPTER SIX',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Identification',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 191,
        category: {
          id: 11,
          chapter: 'CHAPTER SIX',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Exeat',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 192,
        category: {
          id: 11,
          chapter: 'CHAPTER SIX',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Hostel Life',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 193,
        category: {
          id: 11,
          chapter: 'CHAPTER SIX',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Policy on Reading',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 194,
        category: {
          id: 11,
          chapter: 'CHAPTER SIX',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Inter-Personal Relationship',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 195,
        category: {
          id: 11,
          chapter: 'CHAPTER SIX',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'University Property',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 196,
        category: {
          id: 11,
          chapter: 'CHAPTER SIX',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Environmental Issues',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 197,
        category: {
          id: 11,
          chapter: 'CHAPTER SIX',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Dress Code',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 198,
        category: {
          id: 11,
          chapter: 'CHAPTER SIX',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Offences and Recommended Sanctions',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
    ],
  },
  {
    id: 12,
    chapter: 'CHAPTER SEVEN',
    is_bold: true,
    is_capital_letter: true,
    is_italic: false,
    sub_category: [
      {
        id: 199,
        category: {
          id: 12,
          chapter: 'CHAPTER SEVEN',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'University Reward System',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 200,
        category: {
          id: 12,
          chapter: 'CHAPTER SEVEN',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Objectives of JABU Reward System',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 201,
        category: {
          id: 12,
          chapter: 'CHAPTER SEVEN',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Forms of Rewards',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
    ],
  },
  {
    id: 13,
    chapter: 'CHAPTER EIGHT',
    is_bold: true,
    is_capital_letter: true,
    is_italic: false,
    sub_category: [
      {
        id: 202,
        category: {
          id: 13,
          chapter: 'CHAPTER EIGHT',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Discipline of Students',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 203,
        category: {
          id: 13,
          chapter: 'CHAPTER EIGHT',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Statutory Provision',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 204,
        category: {
          id: 13,
          chapter: 'CHAPTER EIGHT',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Disciplinary Action',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 205,
        category: {
          id: 13,
          chapter: 'CHAPTER EIGHT',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Compliance Unit',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 206,
        category: {
          id: 13,
          chapter: 'CHAPTER EIGHT',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Guidance and Counseling Unit',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
    ],
  },
  {
    id: 14,
    chapter: 'CHAPTER NINE',
    is_bold: true,
    is_capital_letter: true,
    is_italic: false,
    sub_category: [
      {
        id: 207,
        category: {
          id: 14,
          chapter: 'CHAPTER NINE',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Social Services',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 208,
        category: {
          id: 14,
          chapter: 'CHAPTER NINE',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Sports and Recreation',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 209,
        category: {
          id: 14,
          chapter: 'CHAPTER NINE',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Banking Facility and Payment of Fees',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 210,
        category: {
          id: 14,
          chapter: 'CHAPTER NINE',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'University Shopping Mall',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 211,
        category: {
          id: 14,
          chapter: 'CHAPTER NINE',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'University Bookshop',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 212,
        category: {
          id: 14,
          chapter: 'CHAPTER NINE',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Catering Services',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
    ],
  },
  {
    id: 15,
    chapter: 'CHAPTER TEN',
    is_bold: true,
    is_capital_letter: true,
    is_italic: false,
    sub_category: [
      {
        id: 213,
        category: {
          id: 15,
          chapter: 'CHAPTER TEN',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Health Services',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 214,
        category: {
          id: 15,
          chapter: 'CHAPTER TEN',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Spiritual Healing and Deliverance',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 215,
        category: {
          id: 15,
          chapter: 'CHAPTER TEN',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Student Rehabilitation Centre',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 216,
        category: {
          id: 15,
          chapter: 'CHAPTER TEN',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Medical Examination and Health Care Delivery',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
    ],
  },
  {
    id: 16,
    chapter: 'CHAPTER ELEVEN',
    is_bold: true,
    is_capital_letter: true,
    is_italic: false,
    sub_category: [
      {
        id: 217,
        category: {
          id: 16,
          chapter: 'CHAPTER ELEVEN',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Student Association',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 218,
        category: {
          id: 16,
          chapter: 'CHAPTER ELEVEN',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Student Unionism',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 219,
        category: {
          id: 16,
          chapter: 'CHAPTER ELEVEN',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Other Associations',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 220,
        category: {
          id: 16,
          chapter: 'CHAPTER ELEVEN',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Qualification Requirements for Office Holders',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
    ],
  },
  {
    id: 17,
    chapter: 'CHAPTER TWELVE',
    is_bold: true,
    is_capital_letter: true,
    is_italic: false,
    sub_category: [
      {
        id: 221,
        category: {
          id: 17,
          chapter: 'CHAPTER TWELVE',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Arrival to Campus',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 222,
        category: {
          id: 17,
          chapter: 'CHAPTER TWELVE',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Use of Personal Vehicle by Students on Campus',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 223,
        category: {
          id: 17,
          chapter: 'CHAPTER TWELVE',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Procedure for Checking into Hall of Residence',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 224,
        category: {
          id: 17,
          chapter: 'CHAPTER TWELVE',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Procedure for Leaving Campus during Semester',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 225,
        category: {
          id: 17,
          chapter: 'CHAPTER TWELVE',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Departure from Campus on Vacation',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
    ],
  },
  {
    id: 18,
    chapter: 'CHAPTER THIRTEEN',
    is_bold: true,
    is_capital_letter: true,
    is_italic: false,
    sub_category: [
      {
        id: 226,
        category: {
          id: 18,
          chapter: 'CHAPTER THIRTEEN',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Matriculation Oath/Code of Conduct',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 227,
        category: {
          id: 18,
          chapter: 'CHAPTER THIRTEEN',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Student Code of Conduct',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
      {
        id: 228,
        category: {
          id: 18,
          chapter: 'CHAPTER THIRTEEN',
          is_bold: true,
          is_capital_letter: true,
          is_italic: false,
        },
        name: 'Conclusion',
        is_bold: false,
        is_capital_letter: false,
        is_italic: false,
        content: [],
      },
    ],
  },
];
